version: '3'

services:
  php:
    build: .docker/php7.4-fpm
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/local_db?serverVersion=8.0
    volumes:
      - ./:/var/www/
      - ./logs/symfony:/var/www/symfony/app/logs
  nginx:
    build: .docker/nginx
    ports:
      - 8000:80
    volumes:
      - ./logs/nginx/:/var/log/nginx
###> doctrine/doctrine-bundle ###
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
